[package]
name = "rays"
version = "0.1.0"
authors = ["Mikko Loponen <mikko.loponen@iki.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.7"
assert_approx_eq = "1.1.0"
rand = "0.7.3"